### ISSUE TITLE
Community Building Plan

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#1]
Focus on fleshing out CBP. (Especially for producers). Include frequency of contacting producers (and team).

**Comment by porteriffic** [comment]
Work with Cassini, Vivek, and Chaz.

**Comment by porteriffic** [comment]
Tag @mitpress on Twitter so they can retweet.

**Comment by porteriffic** [comment]
Dedicate a section to Social Media Prep

**Comment by porteriffic** [comment]
Located in Google Drive. CD 2.1.5 Community Building Plan.

https://docs.google.com/document/d/1qOUdULI8sq3-Lls5S6obyZDaVqEG_tt4aHdpKh75S5w/edit

**Comment by porteriffic** [comment]
Added a few more things. Would like to sit down with @cassininazir to talk about it more.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#160
