### ISSUE TITLE
Summer Plan

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#17]
Put together a summer plan for Creative Disturbance

**Comment by porteriffic** [comment]
Compile list of those available over the summer

**Comment by cassininazir** [comment]
Begun the document at https://docs.google.com/document/d/18uVPW-JRWcBVCAPnM9_SaCV_Qr3CyokumNdmArVyD4c/edit

**Comment by cassininazir** [comment]
This is now in [CD 1.2.3 Summer Plan] (https://docs.google.com/document/d/18uVPW-JRWcBVCAPnM9_SaCV_Qr3CyokumNdmArVyD4c/edit). Closing.
