### ISSUE TITLE
set up intellectual dating trackign system and report on them at team meeting

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#24]
we need an excel sheet to track all intellectual dating opportunites
and help make sure they are followed up on 

this one needs to be added to the tracking list

roger

Rebekah, Susan,

I hope both of your weeks are treating you well! I had the pleasure of meeting Rebekah in person the other day and found out that she has a history of interest in the geosciences. Rebekah Nix is one of the producers for the Big Dreams? Big Data! channel and Susan Eriksson is the producer for the Art & Earth Science Channel. I told Rebekah about your channel, Susan, and thought you both should talk! 

Almost happy Earth Day!

-- Best,
Stephanie Brisendine

**Comment by porteriffic** [comment]
Already created and in Google Drive. CD 2.1 Community Involvement Tracking Sheet.

https://docs.google.com/document/d/1qOUdULI8sq3-Lls5S6obyZDaVqEG_tt4aHdpKh75S5w/edit
