### ISSUE TITLE
approval of fengineer channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#26]
Eun AH lee has met with me and described her proposal to start
a channel called FEMGINEER

i am approving this channel and have asked her to fill out the producer 
form

roger

**Comment by porteriffic** [comment]
Great! I will get in touch with her before this Friday's meeting. Still working on Earth Day.

**Comment by porteriffic** [comment]
Touched bases with Eun Ah. Will need a podcast from her to go up when the Femgineers Channel goes live. Logo is in the works.
