### ISSUE TITLE
Email Ann Maria De Mars (Ronda Rousey's mom)

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#30]
Ask Anna Maria De Mars if she can talk about STEM careers??? Possible podcasts?

**Comment by porteriffic** [comment]
annmaria@thejuliagroup.com

**Comment by cassininazir** [comment]
Thanks, @kkondas for finding the email address! @porteriffic would love to see this happen.

**Comment by porteriffic** [comment]
Yes, thank you, @kkondas! This will be my summer project! :+1:

**Comment by porteriffic** [comment]
I'll email her once I get my official Creative Disturbance email address linked with my current one so I don't look like some creeper.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#158
