### ISSUE TITLE
finalise ashton's job description

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#33]
cassini
i have made you ashton;s official supervisor-this means you have
to approve his time sheets evert two weeks

also as part of this can you take a look at his job description
in the job description document and clean it up/finalise it

include also training plan 
including cisco jabber system and echo360

roger

**Comment by cassininazir** [comment]
@amb141330 including you on this: 

Have gone through and edited the (Job Descriptions doc, CD 1.1.9) [https://docs.google.com/document/d/1S_gCMBh_bJ-geYY_OQQ_1PgPBMYz1pMAypJR0ksYJSU/edit], see 11. Ashton Brilliante.

@amb141330 Please review and let me know if you have any questions or if you feel anything was left out.
