### ISSUE TITLE
send out call for polyglot podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#34]
josephine
can you
edit/clean up for typos
check the email address
check/add to the language list

then send out to all producers and voices immediately

thanks

roger

CALL FOR PODCASTS TO ALL CREATIVE DISTURBANCE PRODUCERS AND VOICES

Creative Disturbance International POLYGLOT DAY June 21 2015

Creative Disturbance is pleased to feature POLYGLOT day to promote linguistic and disciplinary diversity on June 21 2015.

Every language, every discipline, is a reservoir of deep contextual knowledge and wisdom.

Creative Disturbance seeks to detect and reinforce unlikely connections between the ways of knowing 
represented by different languages and different disciplines, while reinforcing the importance of deep 
diverse disciplinary and linguistic knowledge.

We currently have podcasts in the following languages:

Portuguese, Arabic, French, English, Spanish.

We are seeking from you podcasts in other languages. Please drop us an email at

feedback.createdisturb@gmail.com If you would like to do a podcast in another language 
or can recommend someone we should contact.

We currently have podcasts from disciplinary experts in:

Astrophysics, Music, Geology, Computer Science, Visual Art, Design, Nuclear Physics, 
Economics, Theater, Engineering,Sculpture, Philosophy.Art History, Chemistry and others.

We seek podcasts from experts in other disciplines. Please drop us an email at

feedback.createdisturb@gmail.com

The Creative Disturbance Team

**Comment by porteriffic** [comment]
Email has been sent out to both Producers AND Voices
