### ISSUE TITLE
Decide Theme for July

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#35]
corey
at the next production meeting please organise the group to decide
the july theme and start soliciting podcasts

this needs to be done by may 12 latest

roger

**Comment by porteriffic** [comment]
**Ideas:**

July 8: Video Games Day
July 11: World Population Day
July 13: Embrace Your Geekness Day
July 14: Josephine's Birthday (Just kidding. But not really. But just kidding)
July 15: World Youth Skills Day
July 30: International Day of Friendship

**Comment by porteriffic** [comment]
One thing to consider about July 13: What does "geek" mean to an international community?

**Comment by coreysmart92** [comment]
Embrace Your Geekness Day. Does it need to be renamed or presented day?

**Comment by rmalina** [comment]
geek is not an internationally understood word culturally

**Comment by porteriffic** [comment]
@coreysmart92 Let's add this to the agenda for Monday's meeting (5/25) to rediscuss.

**Comment by coreysmart92** [comment]
Tabled to next Sound meeting on 6/7/15.

**Comment by rmalina** [comment]
you really need to decide the july theme-you are not leaving much time to generate
new podcasts related to the theme you pick !!

**Comment by coreysmart92** [comment]
World Youth Skills Day or Video Games Day. Decide between the two. First one is very broad and the second is rather narrow.

**Comment by rmalina** [comment]
my vote is for world youth day

**Comment by porteriffic** [comment]
July theme is World Youth Skills Day. Also, decided one for August. Will as the community in the future for input. Possibly cast votes and such.
