### ISSUE TITLE
Gmail Voices

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#37]
Compile list of all Voices on CD

**Comment by rmalina** [comment]
i am sure stephanie has an email list- but it needs to be systematicised so new
voices are added to it by the production team as they post new podcasts

new voices should be being informed when their podcast just went up

roger

**Comment by cassininazir** [comment]
Josephine, Anvit can get you a list of voices that are on the website. He can also tell you whether we have their email addresses in the online database. If we aren't tracking, please have him open a task to do so.

Sent from my iPhone

On May 5, 2015, at 3:26 PM, rmalina <notifications@github.com<mailto:notifications@github.com>> wrote:


i am sure stephanie has an email list- but it needs to be systematicised so new
voices are added to it by the production team as they post new podcasts

new voices should be being informed when their podcast just went up

roger

�

**Comment by porteriffic** [comment]
These are all the emails of Voices. I've contacted Anvit. Will need a little more time (I had one last final today), expect the email to be sent out tomorrow. Sorry for the delay.

Adrian Avendaño

Ana Rita Fonseca

Andrew Scott

Brian Burhnam

Carolyn DeCristofano

Carolyne Ojwang

Citalli Sanchez

Craig Anderson

Diane Burko

Florian Grond

Gustavo Andres Vallejo Garcia

Huda Hashim

Humphrey Muturi

Isabel Meirelles

Jaki Opollo

Jean-Marc Chomaz

Jeremy Johnson

Jillian Rond

John Ippolito

Julian Voss-Andreae

Justo Asikoye

Kang Zhang

Karen Doore

Kathryn de Ridder-Vignone

Leslie Davis

Liliane Lijn

Lindsey Joyce

Loris Greaud

Maarten Noyons

Manuel de Anda Villa

Maximillian Schich

Michael Punt

Mike Winters

Mohamed Aziz Chafchaouni

Morgan Meyer

Nanjing Gao

Neel Kar

Nicolas Collins

Oliver Kreylos

Patricia Correia

Paul Fishwick

Pauline Oliveros

Perrine Mathieu

Philip Ball

Raphael DeLuzio

Robert Root-Bernstein

Robertina Sebjanic

Ryan McMahan

Samuel Viana

Sean B. Carroll

Sharon Hewitt

Sophia Roosth

Steve Bull

Sundar Sarukkai

Tami Spector

**Comment by rmalina** [comment]
can you send the email to producers now and then to voices when you have the list- we have to give them time to do podcasts for polyglot. roger

**Comment by porteriffic** [comment]
Yes. Email to producers sent. Will send email to Voices tomorrow.

**Comment by porteriffic** [comment]
Email to Voices has been sent out.
