### ISSUE TITLE
Nahum Mantra Intellectual Dating

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#38]
can you add this to the intellectual dating tracking list
also he can do it in spanish for the june 21 polyglot day

i could do it in english-but if you can find someone to do
it in spanish that would be great

he is in mexico city

roger

nahum.mantra@gmail.com
Nahum
Apr 6

to roger 
Dear Roger,

Thank you so much! I have put so much energy in this project for two years and now glad it is seeing the light of day. 

I am happy to work on some podcasts for creative disturbance and a Leonardo article. How can i proceed with these ideas?

Abrazos,
Nahum 
***
Nahum
www.nahummantra.org
contact@nahummantra.org
twitter: @nahummantra
skype: nahummantra

**Comment by porteriffic** [comment]
I've added him to the tracking sheet. Are you following up with him to do a podcast? I can help find someone who can speak Spanish to host.

**Comment by rmalina** [comment]
josephie-can youfollow up to get this scheduled in spanish before june 21 ?

the mexican studens that yvan is friendly with could surely help

i am happy to do one in english

roger

**Comment by porteriffic** [comment]
Sure. I can work with Yvan to get this up before June 21st.

**Comment by porteriffic** [comment]
Contacted Yvan, Dario and Manuel would be willing to record with Nahum. Just contacted Nahum, waiting to hear back.

**Comment by porteriffic** [comment]
Trying to put Nahum Mantra in contact with Dario and Manuel. Last heard from him 5/15

**Comment by porteriffic** [comment]
Introduced Nahum to Dario and Manuel. They will be collaborating to do a podcast in Spanish. This has been added to the [Community Involvement Document](https://drive.google.com/drive/folders/0B5c7wZNmEjILVE5tRWhsQU9TcGc/0BwvQhnxKj6jFVVV3U3pvMEstN1E/0B47T3_SpQdTWfjBockExZkdjQmt4RE0yeGNDX082M3hlZ1dDNDNRTE9UaWVrc0NrR0RXVTQ) located in the Google Drive.

**Comment by porteriffic** [comment]
Will email Nahum to see how things are going this week.

**Comment by porteriffic** [comment]
Emailed Nahum a couple weeks back. Still have not heard back. Possibility we might not get a podcast in Spanish from him, which is okay because we have another podcast in Spanish in the works.

**Comment by porteriffic** [comment]
Nahum and Dario were able to do a podcast in time for Polyglot. Will update tracking sheet.
