### ISSUE TITLE
Add $500 Kickstarter Donors as "Disturbing Advisors"

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#39]
josephine
we need to add all kickstarter donors above $500 to the team page
as disturbing advisors and involve them in selecting the students

roger

here is one

Arun Augustine

 #8
 4 backed
 Richardson, TX
 arun@planaut.com
InfoSend message
Survey response
Responded on May 1 2015
Name & address
Arun Augustine
1235 Brookdale Ave
Mountain View CA 94040-3023
UNITED STATES
What size(s) would like your T-shirts to be? (Available sizes: XS, S, M, L, XL) Example answer: 1 XS, 1 M.
M
Are you interested in serving on the DAB (Disturbing Advisory Board)?
Yes
Collected 
$501 pledged

Reward: $500

Shipping: United States

Everything offered above; PLUS you will be invited to serve on our DISTURBING ADVISORY BOARD for no less than one year. As a DAB Member you will help us select the awarding of grants to students around the world to spark conversations and regional gatherings of the intellectually curious in their area; PLUS you can add SIX MORE "CONVERSATIONS" (podcasts) (Total of 19) to our VOICES OF THE CROWD Channel; PLUS you'll be invited to PARTICIPATE IN FOUR MORE "CONVERSATIONS" IN OTHER CHANNELS of Creative Disturbance (Total of 10).

Ships anywhere in the world

**Comment by rmalina** [comment]
here is a second disturbing advisor
roger

Name & address
Dr. Diane Gromala
834A Thirteenth St
New Westminster BC V3M 4M9
CANADA
What size(s) would like your T-shirts to be? (Available sizes: XS, S, M, L, XL) Example answer: 1 XS, 1 M.
XL
Are you interested in serving on the DAB (Disturbing Advisory Board)?
yes
Collected 
$500 pledged

Reward: $500

Shipping: Canada

Everything offered above; PLUS you will be invited to serve on our DISTURBING ADVISORY BOARD for no less than one year. As a DAB Member you will help us select the awarding of grants to students around the world to spark conversations and regional gatherings of the intellectually curious in their area; PLUS you can add SIX MORE "CONVERSATIONS" (podcasts) (Total of 19) to our VOICES OF THE CROWD Channel; PLUS you'll be invited to PARTICIPATE IN FOUR MORE "CONVERSATIONS" IN OTHER CHANNELS of Creative Disturbance (Total of 10).

**Comment by rmalina** [comment]
another one
but check with yvan first
roger
Survey response
Responded on Mar 15 2015
Name & address
TINA Anna
17 avenue du Rozier
Résidence du lac appartement 013
61140 Bagnoles de l'Orne
FRANCE
What size(s) would like your T-shirts to be? (Available sizes: XS, S, M, L, XL) Example answer: 1 XS, 1 M.
XL
Are you interested in serving on the DAB (Disturbing Advisory Board)?
NON
Collected 
$500 pledged

Reward: $500

Shipping: France

Everything offered above; PLUS you will be invited to serve on our DISTURBING ADVISORY BOARD for no less than one year. As a DAB Member you will help us select the awarding of grants to students around the world to spark conversations and regional gatherings of the intellectually curious in their area; PLUS you can add SIX MORE "CONVERSATIONS" (podcasts) (Total of 19) to our VOICES OF THE CROWD Channel; PLUS you'll be invited to PARTICIPATE IN FOUR MORE "CONVERSATIONS" IN OTHER CHANNELS of Creative Disturbance (Total of 10).

Ships anywhere in the world

**Comment by porteriffic** [comment]
@cassininazir Will need your help with this. I can gather the names but will need help getting it up on the website.

**Comment by cassininazir** [comment]
Am assigning this to you, @halclark.

This is dependent on [Podcast #52] (https://github.com/creativedisturbance/podcasts/issues/52). Work with Anvit, Sruthi, Josephine or myself if you have any questions about website editing. 

These updates should appear on the [Meet the Team page] (http://creativedisturbance.org/meet-the-team/), after the Small World Team and before CD Alumni with the heading **Disturbing Advisors**. 

Email @cassininazir with any questions.

**Comment by cassininazir** [comment]
Page updated.
