### ISSUE TITLE
transfer kickstarter implementation duties

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#40]
stephanie will not have finished implementing all the commitments
we made to kickstarter donors before she leaves ( eg the student grants)
we need to discuss with her a to do list and transfer these duties to someone else
roger

**Comment by porteriffic** [comment]
Meeting with Stephanie tomorrow to discuss

**Comment by porteriffic** [comment]
Spoke with Stephanie about Kickstarted duties. She is wrapping up these and should be done by the time she leaves. Will work with her to get the perk fulfillment mailed out.
