### ISSUE TITLE
Podcast in Bengali with Dhru

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#41]
josephine

yeah ! hope you can make this happend
roger

Dhruba Deb <dhrubadeb@gmail.com>

cc:	Debayan Ghosh <debayanghosh.deb@gmail.com
Hi Roger,

I saw the email on call for podcasts on additional languages. I was talking to my friend Debayan (cc'd here) on East Indian culture and its influence and manifestation in art and science. We can record a podcast over skype in Bengali (along with English translation in a second podcast). Please let me know your thoughts.

There are two other podcasts I am working on - How art and science are intertwined with Samuel, and 3 women artists in the cancer-art project. Hopefully, we can get both done in this summer.

I'm sorry I could not make it to any ArtSci party. Lots of stuffs to take care of by the end of this PhD. Again, hopefully, will be better by the end of this summer.

Best

**Comment by porteriffic** [comment]
Contacted Dhru. Will be coordinating with him during this week.

**Comment by porteriffic** [comment]
Last heard from Dhru 5/12. He is coordinating with his podcast Voices and will update me accordingly.

**Comment by porteriffic** [comment]
Still haven't heard from Dhru.

**Comment by porteriffic** [comment]
Never heard from Dhru. Will use his podcast for a later date whenever we get it.
