### ISSUE TITLE
Contact Lina About Graphic Design

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#43]
See if Lina will take over Stephanie's graphic design responsibilities.

**Comment by cassininazir** [comment]
@linamoon, would like to begin phasing you into doing design work for Creative Disturbance. Could you setup a meeting with @heiwanalady (Stephanie) possibly early next week (May 18 or thereabouts) to discuss? I can Skype in as necessary.

**Comment by cassininazir** [comment]
Magic is happening. Lina and Stephanie meeting tomorrow (May 19) to discuss. @cassininazir will try to Skype in.
