### ISSUE TITLE
Contact these people for Polyglot podcasts

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#46]
Moon Kim (Korean), Darren (German), Stephanie (Japanese)

**Comment by porteriffic** [comment]
@heiwanlady Would you be able to do a podcast in Japanese for Polyglot day?

**Comment by porteriffic** [comment]
@yvantina Are you recording a podcast with Max and Darren for Polyglot Day?

**Comment by porteriffic** [comment]
@amb141330 will contact Moon Kim about recording a podcast.

**Comment by yvantina** [comment]
Yep

**Comment by heiwanalady** [comment]
Ha.. Maybe, maybe not. I would suggest maybe Midori Kitagawa here on
campus. Or if we could somehow get in contact with Joi Ito from the MIT
Media Lab  :)

**Comment by yvantina** [comment]
@heiwanalady @porteriffic @rmalina 
I am trying to get a japanese podcast from friends in Tokyo ;) but please go ahead with Midori K. if you can.. Joichi may be reachable through Roger but not sure he would like to make a podcast though (even in japanese)..that would be awesome..

**Comment by porteriffic** [comment]
@yvantina I'm afraid Roger might be too busy. If you could get a Japanese podcast from your friends that would be great!

**Comment by porteriffic** [comment]
Were able to get one in German and in Japanese. All set for Polyglot Day!

**Comment by yvantina** [comment]
Have just submitted the forms for a Space Art and Culture podcast in Spanish (Nahum Mantra and Ale de la Puente) ..

**Comment by porteriffic** [comment]
There three voices on that podcast correct? Dario, Nahum and Ale de la
Puente?

**Comment by porteriffic** [comment]
Nevermind I saw your notes. Sorry!

**Comment by yvantina** [comment]
Yes
2 podcasts
