### ISSUE TITLE
Create a Style Guide for Dropbox Procedure

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#48]
How to share folders with Producers. How to create a new folder for a channel. What goes in the folder. So on and so forth.

**Comment by porteriffic** [comment]
Will be cleaning up DropBox this week and transitioning Producers over to new folders. Will work on Style Guide once that has been completed

**Comment by porteriffic** [comment]
@cassininazir Would like your feedback. I've created the new folders but the only way I can share is if Dropbox sends an invite. For example, Roger's a producer for multiple channels, he'll multiple emails from Dropbox for each invite I send to him. Not sure how to handle this...

**Comment by cassininazir** [comment]
I think that Roger will be the exception. I can't think of any other producers in the same boat, except perhaps Yvan. Because they are part of the project team, we can setup a folder for them specifically.

**Comment by porteriffic** [comment]
@cassininazir I've assigned Kyle to start helping the team manage Dropbox. I will help send out the emails but after that I will need someone to take over Dropbox issues.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#156
