### ISSUE TITLE
Add Polglot Stats to Current Metrics (June 22nd)

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#51]
add to the regular metrics a section on polyglot stats
on number of podcasts in each language, but also discipline stats

roger

**Comment by porteriffic** [comment]
Will add Polyglot stats to regular metrics for that week.

**Comment by porteriffic** [comment]
Would like to do a small graphic for metrics after Polyglot Day to send to Producers and Voices. @heiwanalady or @linamoon Would either of you be able to help me?

**Comment by porteriffic** [comment]
Metrics have been collected. Will add to agenda for Monday 7/6
