### ISSUE TITLE
New Process for Metrics

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/administrative#52]
@porteriffic would like to improve the process for getting and storing metrics. 

Have created the folder [7.0 Metrics] (https://drive.google.com/drive/u/0/folders/0B5c7wZNmEjILVE5tRWhsQU9TcGc/0BwvQhnxKj6jFflhqR29LcG1tRlRwNU9aMkM3SlNfQUppVVZCNkYwUjI4ekRGQVFCVHI4YmM) in Google Drive.

And started the document [2015-05-25 Metrics for Prior Week 17-23 May] (https://docs.google.com/document/d/19JoSFWgsqKOGTPFwi1jD7V5ZtU3x0ZHsw3R8-T1Y3R4/edit) for you. 

Can you use begin adding to this folder using the template provided? 

Close when you have completed your metrics document.

**Comment by cassininazir** [comment]
Am recommending we adapt (Google's HEART framework) [https://www.gv.com/lib/how-to-choose-the-right-ux-metrics-for-your-product] for our metrics: 

- **Happiness**: measures of user attitudes, often collected via survey. For example: satisfaction, perceived ease of use, and net-promoter score.
- **Engagement**: level of user involvement, typically measured via behavioral proxies such as frequency, intensity, or depth of interaction over some time period. Examples might include the number of visits per user per week or the number of photos uploaded per user per day.
- **Adoption**: new users of a product or feature. For example: the number of accounts created in the last seven days or the percentage of Gmail users who use labels.
- **Retention**: the rate at which existing users are returning. For example: how many of the active users from a given time period are still present in some later time period? You may be more interested in failure to retain, commonly known as “churn.”
- **Task success**: this includes traditional behavioral metrics of user experience, such as efficiency (e.g. time to complete a task), effectiveness (e.g. percent of tasks completed), and error rate. This category is most applicable to areas of your product that are very task-focused, such as search or an upload flow.

**Research docs**
- http://research.google.com/pubs/pub36299.html 
- http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/36299.pdf

**Comment by porteriffic** [comment]
@cassininazir Should I wait until Sunday night to compile metrics? That's what I've been doing...

**Comment by cassininazir** [comment]
Yes. Hope to make this an automated process at some point.

Sent from my iPhone

On May 22, 2015, at 6:49 PM, porteriffic <notifications@github.com<mailto:notifications@github.com>> wrote:


@cassininazir<https://github.com/cassininazir> Should I wait until Sunday night to compile metrics? That's what I've been doing...

�

**Comment by cassininazir** [comment]
Excellent additions, Josephine. When new forms are up, would like the web team to then focus attention on implementing [BuddyPress] (www.buddypress.org) (it's installed on the production server currently and needs to be configured). Some of what you detailed in the can be compiled from BuddyPress.

**Comment by porteriffic** [comment]
@cassininazir I've added this week's metrics to the document (I had to do it tonight since I won't have time tomorrow night to do it). Didn't have anything from Bitly since no links were used. I'm still unfamiliar with how to access Stitcher stats, so there isn't anything from Stitcher.

**Comment by cassininazir** [comment]
Good. Let's templatize the content we want to watch. Am hoping there's a way for us to automate this.
