### ISSUE TITLE
How can we record Jabber sessions

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/administrative#54]
Find out how we may record Jabber sessions and create a sheet for it. Let's discuss in our Tuesday session.

**Comment by amb141330** [comment]
We can check and see if we can use FRAPS with Jabber sessions. 

http://stream-recorder.com/forum/record-save-capture-jabber-xmpp-video-chat-t9701.html

That link talks about two different options for recording those sessions as well.

**Comment by cassininazir** [comment]
Please connect with Brian Merlo by end of week on this issue.

**Comment by amb141330** [comment]
Waiting to hear back from Brain.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#153
