### ISSUE TITLE
set up new channel " on the margins' with poe johnson as a producer

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#55]
osephine

poe johnsom is setting up a new channel
called "on the margins" and has four podcasts
that need to be put in drop box

can you help him be trained as a producer
with all the necessary forms and cheat sheets
-- 
Roger F Malina

**Comment by porteriffic** [comment]
Will contact Poe Johnson this evening.

**Comment by porteriffic** [comment]
Contacted Poe. Will coordinate with him this week and probably next week.

@heiwanalady He'll need a logo for this channel. Roger says Poe has podcasts already recorded so this logo will be needed sooner than the Femgineers channel I'd imagine.

**Comment by porteriffic** [comment]
Poe now has access to the Dropbox. He has yet to put anything in there and has not responded yet.

**Comment by heiwanalady** [comment]
@porteriffic  Got it. I think this will be a good one for Lina to start. Will email her about it.

**Comment by porteriffic** [comment]
Dropbox is full. I think that's why he hasn't put any podcasts in. Assigned @kkondas to help manage the Dropbox.

**Comment by porteriffic** [comment]
His channel is up and running!
