### ISSUE TITLE
VOTC Podcast with Dave Burraston

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#57]
Contact Dave and give him necessary cheat sheets for making a podcast for Voices of the Crowd.

**Comment by porteriffic** [comment]
Contacted Dave. Waiting to hear back.

**Comment by porteriffic** [comment]
I've given Dave cheat sheets. Waiting to hear back.

**Comment by porteriffic** [comment]
Still no response from Dave. (As of 6/1/2015)

**Comment by porteriffic** [comment]
Still no response from Dave. (As of 6/5/2015)

**Comment by rmalina** [comment]
just put this action on hold-roger

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#151
