### ISSUE TITLE
Renew Expiring UTD Accounts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#58]
stephanie

utd sometimes close student accounts- can you ssend an email to ALL CD team
telling them to tell you if they got an alert of an account closing down so brett
can renew it

roger

I just got an email saying my computer access and net ID will expire in early June. I will be working at the lab over the summer before I leave (July 25) - so will need computer access until then. 

I've Cc'ed Roger so he can confirm.

Best,
Stephanie

**Comment by porteriffic** [comment]
I'm confused. I'm assigned to do this but Roger is talking to Stephanie...?

**Comment by cassininazir** [comment]
@heiwanalady reassigning to you.

**Comment by heiwanalady** [comment]
Done!
