### ISSUE TITLE
Student Grant to Egyptian Student

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#59]
podcast voice haytham nawar teaches at the american university in cairo egypt- he says he has a student that could produce some podcasts

haytham is at Haytham Nawar <haythamnawar@gmail.com>

yvan tina is a liaison as haytham just did a podcast on virtual africa channel

josephine you need to discuss this with stephanie as this would be implemented
after she leaves but you can contact haytham

roger

**Comment by porteriffic** [comment]
@heiwanalady Maybe we can Skype or meet up this week? I'm flexible.

**Comment by heiwanalady** [comment]
@porteriffic I'm available! just let me know a time.

**Comment by porteriffic** [comment]
@heiwanalady Sorry for the late response. Can we Skype tomorrow morning? Around 10?

**Comment by heiwanalady** [comment]
@porteriffic sure, that should work for me.

**Comment by rmalina** [comment]
i am travelling today and cant do a skype but maybe you can go ahead and keep this moving
roger

**Comment by heiwanalady** [comment]
**Just sent Nawar this email:**

Mr. Nawar, 

I work with Yvan Tina and Dr. Roger Malina on Creative Disturbance and am currently coordinating the perk fulfillments for our recent Kickstarter. I believe you mentioned you had an Egyptian student in mind as a potential recipient of our International Student Grant. I would love to discuss this further with you. 

We are in the middle of sculpting our student grant program's terms and conditions and welcome any feedback you might have. Here is a document detailing the current scope of the grant program - feel free to comment! We are also collaborating with a few Portuguese students in Lisbon on this and we'd be happy to connect you. We are very interested in producing content around the globe and welcome different disciplines and languages (we just celebrated International Polyglot Day on our website). 

Please let me know if you have some free time to chat this month and we can set up a Skype meeting! 

Best,
Stephanie Brisendine

**Comment by cassininazir** [comment]
@linamoon including you on this thread.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#150
