### ISSUE TITLE
Album Artworks to be Created

### ISSUE THREAD

**Issue by heiwanalady** [creativedisturbance/administrative#61]
* Rhythmically Inclined (Stephanie)
* On the Margins (Lina)
* Femgineers (Stephanie)

@linamoon 
There is an issue opened already about this, and we can contact Poe Johnson (He will be producer of On the Margins) for more info on the channel - let me know if you need any additional help with this

**Comment by linamoon** [comment]
@heiwanalady got it - is there a process + contact info for him so we can get the info for the channel?

**Comment by heiwanalady** [comment]
@linamoon yes! his email address: poejohnson@gmail.com 
Basically, you can look at his Channel proposal and figure out if there's any inspiration you can derive from his idea that's visual. Show him your iterations and have him involved in the process - however, you don't need to rely on his opinions only. We just want to involve producers in our process.

**Comment by linamoon** [comment]
@heiwanalady is the Channel proposal in the Google Drive? Seeing a Channel Proposal Form (Responses) but nothing seems to be on there.

**Comment by heiwanalady** [comment]
@linamoon Channel Proposal entries are in wufoo. https://dmarlett.wufoo.com/entries/creative-disturbance-new-channel-proposal-form/ 
Make sure to login with the new password (https://docs.google.com/document/d/1ipNxXHlGpEPgllR6QBQ2HF6vrOWRgLuhnngcUIqClxU/edit)

*Channel description:*
Within The Margins seeks to provide a space for thinkers, both inside and outside of the academy, to contextualize the way that marginalized people --in terms of race,ethnicity, gender, class, and sexual orientation-- are formed by technology, science, media, and art institutions and systems

**Comment by linamoon** [comment]
@heiwanalady is there also a suggested deadline? (obviously before podcast goes up)

**Comment by heiwanalady** [comment]
@linamoon unfortunately Poe already has several podcasts ready to go (and we were notified late) so your deadline is as soon as possible. :) I would say you're looking at about a week. Is that enough? 

If not - you can always contact Poe and/or the sound team to say you need more time. Let me know!

**Comment by linamoon** [comment]
@heiwanalady sounds good enough :) is there a suggested deadline in general for podcasts? I guess I would look at the production tracking sheet?

**Comment by heiwanalady** [comment]
@linamoon Yeah that would be your best bet on when the podcasts would come out. The podcast tracking sheet is updated every Monday.

**Comment by cassininazir** [comment]
Closing this. Open a new issue for Femgineers when that channel is approved.
