### ISSUE TITLE
Metrics Graphic for Polyglot Day

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#63]
@linamoon Would like to create a small graphic like this one post Polyglot Day to send to Producers: 

![creativedisturbance_diversitystats](https://cloud.githubusercontent.com/assets/10836612/7946836/cc2caea2-093e-11e5-8769-32bd5418a2ca.png)

**Comment by linamoon** [comment]
@porteriffic Yes, can do - would you just need it as a jpeg?

**Comment by porteriffic** [comment]
@linamoon I believe Stephanie made a png. We'll give you the metrics for this after Polyglot Day.

@heiwanalady Will a jpeg work?

**Comment by heiwanalady** [comment]
@porteriffic JPEG.. Png... Anything works. You only need png if there's
transparency

On Tuesday, June 2, 2015, porteriffic <notifications@github.com> wrote:

> @linamoon <https://github.com/linamoon> I believe Stephanie made a png.
> We'll give you the metrics for this after Polyglot Day.
>
> @heiwanalady <https://github.com/heiwanalady> Will a jpeg work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativedisturbance/administrative/issues/63#issuecomment-108176604>
> .
>


-- 
--- Sent from Stephanie's iPhone ---

**Comment by porteriffic** [comment]
Emailed the community metrics for Polyglot Day.
