### ISSUE TITLE
With The Margins Folder

### ISSUE THREAD

**Issue by kkondas** [creativedisturbance/administrative#64]
Corey, I was able to alleviate some space on the dropbox, but the folder "Within The Margins", which is the folder that Poe Johson put all of his podcast in is eating up a lot of the space. It's mandatory that we get those podcast sassigned to the sound team and archived ASAP so we have more room in the dropbox.

**Comment by coreysmart92** [comment]
I am scheduling them, but for short term I am moving them over to the Google drive [Needs Editing] (https://drive.google.com/drive/folders/0B5c7wZNmEjILVE5tRWhsQU9TcGc/0BwvQhnxKj6jFVVV3U3pvMEstN1E/0BwvQhnxKj6jFVU1rSGYwdmtIVmc/0B4M0we6AguJVNmV6dy11YkxjeUk) .
Close: When all files are on Google Drive.

**Comment by coreysmart92** [comment]
Closing it is now in [Needs Editing] (https://drive.google.com/drive/folders/0B5c7wZNmEjILVE5tRWhsQU9TcGc/0BwvQhnxKj6jFVVV3U3pvMEstN1E/0BwvQhnxKj6jFVU1rSGYwdmtIVmc/0B4M0we6AguJVNmV6dy11YkxjeUk/0B0RS2YDJUln1fkI5Yi1paTBJejBPRmNldFJRRnB0c181S0ZON2xyUzRJU0ZpRkxra2thR0E) folder on google drive.
