### ISSUE TITLE
Kickstarter Fulfillment

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#65]
stephanie
where do we stand on sending out tee shirts and stickers

roger
Lori Ibarra Drozd said:
I believe I responded to the survey, but I haven't received my sticker yet. Can we check and see if my survey response was submitted? Thank you!

**Comment by heiwanalady** [comment]
Will give a full report by Friday!

**Comment by heiwanalady** [comment]
Sent! Will do a follow-up email to those who have not responded this week.
