### ISSUE TITLE
Appoint First Creative Disturbers from Kickstarter Funds

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#66]
i had very succesful meetings in lisbon with patricia correia, anna rita fonseca and sam meyler
they have accepted to be our first creative disturbers with three $1000 grants to crowd source content
their channel will be called "roots of curiosity- with a formal launch planned for october when they have a book coming out with the same title

stephanie-i dont know if you have time to do this before you leave ! but we need to put a formal
invitation packagte together tosend them with terms and contidions and also instructions on how to set up a new channel and all the cheat sheets etc

anyway lets discuss in a skype

roger

**Comment by heiwanalady** [comment]
@rmalina - I will try and do as much as I can before I leave! I'm glad the
meeting went well! How was Lisbon?!

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#148
