### ISSUE TITLE
no forms left on wufoo

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#67]
i am getting this message on wufoo
You have 3 forms left! Upgrade for more!
Upgrade Your Forms!
Never Run Out: Get unlimited forms & reports.
Online Payments: Accept payments on your forms.
Admin Users: Add multiple users to your account.

what do i need to do so i can keep filling out forms-or when are we moving to the new forms ?

not sure who this shouild be assigned to

roger

**Comment by porteriffic** [comment]
@rmalina That message has always been there. It's a little confusing. What it is actually saying is we have 3 form types left. We currently have 8 different form types (New Podcast Form, Guest Release Form, etc.). 

@cassininazir Correct me if I'm wrong. I think we addressed this earlier this semester.

**Comment by rmalina** [comment]
well i still got that message and it IS confusing-but its moot if we are about to start using the new form system
