### ISSUE TITLE
Dropbox Clean Up

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#68]
the voices from the crowd drop box still has sound files in it that have already appeared on creative disturbance and need to be moved out of drop box

whose job is it to move files out of drop box once they are posted on creative disturbance ?

for instance the ansari podcast is on line but still in the drop box

roger

**Comment by porteriffic** [comment]
@kkondas Can you please look into this? Needs to be done ASAP.

**Comment by rmalina** [comment]
josephine-standard operating tasks should not be assigned to faculty members but to one of the production team-this is a standard operationg issue.roger

**Comment by porteriffic** [comment]
@halclark Please go through the Dropbox and prep it for Polyglot Day. Reach out to @amb141330 or I if you need assistance or have questions on what "prepping" entails.

**Comment by porteriffic** [comment]
@halclark Please go through Dropbox and clean up. We need to transition producers over to new folders and remove the old ones. Ask @coreysmart92 or myself if you need assistance. Please have this done by July 7. Close when completed.

**Comment by cassininazir** [comment]
DropBox has been upgraded to Pro account.
