### ISSUE TITLE
update team page to move students who have graduated to alumni section

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#70]
please update the team members page to move hte studenst who have graduated to
the alumni section

leavel their bios and pictures there

tell them we are doing this and that they are still members of the team
 make sure we have their non utd email addresses and add them to our email lists

tell them they can nominate or recommend people for podcasts at any time

roger

**Comment by porteriffic** [comment]
Emailed students that have graduated and moved them to "Alumni" section.

**Comment by rmalina** [comment]
josephine-see stephanies email about bold roast channel and maybe trying to keep interested alumnae involved ! roger
