### ISSUE TITLE
remove the graduated students fro  github

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#71]
remove hte graduated students from github so they arent getting emails
roger

**Comment by porteriffic** [comment]
Removed Sruthi and Vivek. I'll remove Stephanie once she leaves for Japan. Same for Anvit.

**Comment by rmalina** [comment]
josephine
but see stephanie's idea of community building with alumnae of the lab
can you discuss with stephaine how we might do this ?
roger
