### ISSUE TITLE
Email to Producers (Metrics, Podcasts, etc)

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#73]
Email community about the following:

- ~~Emails about upcoming days in July and August~~
- Let producers know how their channel is doing and give them stats. 
   - Emailed Scot and Tim so far. Will email more over the weekend and after I collect stats for Polyglot.
- If a producer isn't bringing in podcasts, let them know and encourage them and offer assistance.
   - Adventures of Crowdfunding will be archived. David Marlett won't be bringing in anymore podcasts for this channel.

Use Cassini's [tracking sheet](https://docs.google.com/spreadsheets/d/1JUtI3ecGsmmmIR9dKtSGxkuNFcKvmzhXc2ND69MSvd4/edit#gid=90106257)

**Comment by porteriffic** [comment]
Started working on drafts for the these emails. Will send out top priority ones tomorrow and the others on Thursday.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#146
