### ISSUE TITLE
Transfer of Producer for The Bold Roast

### ISSUE THREAD

**Issue by heiwanalady** [creativedisturbance/administrative#76]
@porteriffic , Just got off a Skype with @rmalina  

We need to discuss how to transfer producer duties to different person for The Bold Roast as well as discuss the possibility of using ArtSciLab alumni/alumna as the producers for the channel? 

How do we keep the alumni/alumna involved after they've graduated and maintain that network? 

I'd be open to co-producing on a team of students if that's a possibility. Would be more efficient I think.

**Comment by sayloo** [comment]
I'd be more than happy to voluntarily work for the lab :+1:

**Comment by porteriffic** [comment]
This issue has been on the back burner for a while. I'd be ore than happy to meet up to discuss. 

@sayloo That would be awesome!

**Comment by heiwanalady** [comment]
@rmalina @cassininazir @porteriffic @sayloo @anvit @heiwanalady

Josephine and I met this morning about how to handle this - and we are going to extend the invitation to Sruthi, Anvil, Cathryn and myself to run The Bold Roast together as an alumnae/alumna team :)
Still need to email Cathryn about this. I'm sure it will be easy to run the channel with 4+ people available to respond to questions or approval of podcasts etc.

**Comment by rmalina** [comment]
i think this is a FANTASTIC idea !!

**Comment by porteriffic** [comment]
Sruthi has agreed to be a producer!

**Comment by porteriffic** [comment]
Anvit and Stephanie agreed to be producer as well. Have not heard back from Cathryn

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#145
