### ISSUE TITLE
Adventures in Crowdfunding

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/administrative#77]
@cassininazir @heiwanalady @rmalina Should we leave this channel up? It's been idle for quite some time.

**Comment by rmalina** [comment]
let me check with david marlett what he wants to do= roger

**Comment by rmalina** [comment]
i send this to david
david



minor item- we are reviewing the creative disturbance channels and a number
of them have been fairly inactive ( including my space and the arts channel)

are you planning any podcasts in the new two months on your two channels ?


-- 
Roger F Malina

**Comment by porteriffic** [comment]
Duplicate.
