### ISSUE TITLE
Archive Adventures in Crowdfunding Channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#78]
david marlett doest plan to produce any more podcasts for the crowdfunding channel ( he will for cinemersia) - maybe we should create an archive section for channels that are no longer active ?
or find someone else to produce podcasts for the crowdfunding channel ?
roger @cassininazir @coreysmart92

**Comment by porteriffic** [comment]
@anvit Is there a way we can archive the Adventures in Crowdfunding channel? If not, can we create an archive page?

**Comment by rmalina** [comment]
we need to keep the podcasts up- but somehow indicated that the channel is archival
and we can solicit crowdfunding related podcasts but will need a new channel producer
roger

**Comment by anvit** [comment]
@porteriffic There isn't a way to archive the channels at the moment but I can create a separate archive page and set up a simple process for showing the archived channels only on the archives page.

**Comment by porteriffic** [comment]
@anvit Yes, I think ideally we'd like to still have the channel and podcasts available for listening or downloading so a separate page would work, I think. I'll be in the lab Thursday morning around 10am if you'd like to discuss.

**Comment by anvit** [comment]
@porteriffic Will you still be here around 11am? I'll try coming earlier but I most probably will reach the lab around 11.

**Comment by porteriffic** [comment]
@anvit Yup! I'll be there. I have to leave around 11:30 though. See you then!

**Comment by heiwanalady** [comment]
@porteriffic will you still be meeting me and Cassini at the lab at 10am on
Thursday?

On Wednesday, June 24, 2015, porteriffic <notifications@github.com> wrote:

> @anvit <https://github.com/anvit> Yup! I'll be there. I have to leave
> around 11:30 though. See you then!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativedisturbance/administrative/issues/78#issuecomment-115044392>
> .
>


-- 
--- Sent from Stephanie's iPhone ---

**Comment by porteriffic** [comment]
@heiwanalady Yup! I'll be there!

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#144
