### ISSUE TITLE
dead link on podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#83]
dead link on podcast

http://creativedisturbance.org/podcast/putting-the-user-back-in-user-experience/

**Comment by porteriffic** [comment]
@anvit Not sure why the page looks the way it is. This is an old podcast right?

**Comment by anvit** [comment]
@porteriffic Yes, it's an old one. It seems like the description had embed external slides within the webpage in addition to the link and that was overlapping with the rest of the content on the page. I've removed that.

**Comment by anvit** [comment]
@porteriffic For the podcast link - the link is correct but audio file is a .wav file and not a .mp3 and the audio player on the site expects an mp3 link. This behavior is also inconsistent across different browsers(for example: chrome will still show the audio player and play the file correctly, while firefox doesn't show the audio player). The best fix would be to convert the .wav to an .mp3 and use that link.

**Comment by porteriffic** [comment]
@anvit Thanks for taking care of that!

@coreysmart92 or @halclark Can one of you please convert this podcast file from .wav to .mp3 and make sure it's functioning on the website correctly on different browsers. Close issue when complete.

**Comment by porteriffic** [comment]
@coreysmart92 @halclark Has this been taken care of?!
