### ISSUE TITLE
Complete First Email Template

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/administrative#84]
@heiwanalady would like to unveil the first email template this week (29 July-4 July). @porteriffic has an email that she will be sending out on Wed to get input for **World Youth Skills Day**.

**Comment by porteriffic** [comment]
@heiwanalady I can be at the lab on Wednesday morning to discuss/implement.

**Comment by heiwanalady** [comment]
@porteriffic I will be there on Wednesday. How about 10/11am?

On Monday, June 29, 2015, porteriffic <notifications@github.com> wrote:

> @heiwanalady <https://github.com/heiwanalady> I can be at the lab on
> Wednesday morning to discuss/implement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativedisturbance/administrative/issues/84#issuecomment-116834115>
> .
>


-- 
--- Sent from Stephanie's iPhone ---

**Comment by porteriffic** [comment]
I can be there as early as 10am. Whichever works!

**Comment by cassininazir** [comment]
Have a meeting from 10-noon Wed. Can meet with you after.

Cassini Nazir

Clinical Assistant Professor,
School of Arts and Technology and Emerging Communication
The University of Texas at Dallas

**Comment by porteriffic** [comment]
First email template sent out for World Youth Skills Day
