### ISSUE TITLE
develop clearer guidelines for people to submit their own podcasts

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#85]
to help create a back log of podcasts i have send an email to leonardo authors to submit their own podcasts (ie that the record themselves and send it)

the cheat sheet i sent them is the one for producers but i really think we need one redone for people to submit their own podcasts

ie Creative Disturbance Podcast Submittion Guidelines

can you rework this and keep in mind people who are NOT on our team of producers would be getting this so it needs to be addressed to people who dont understand our internal processes

here is the doc

Document CD 2.2.2.7
@porteriffic 
roger

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#141
