### ISSUE TITLE
possible new channel Climate sHeros

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#87]
possible new channel for discussion monday
@coreysmart92 @porteriffic 
 from tara deporte

she has this podcast series called climate (s)heros of women in climate change
Wonderful!  
Also, feel free to repost and share our current podcasts for Human Impact Stories:  HumanImpactsInstitute.org/HumanImpactStories

is there an easy way for us to create a channel with her as producer and
then grab her podcasts as she puts them up onto sound cloud without
her having to fill out all our forms for each podcast ?

the answer may be no

roger

Tara DePorte
Executive Director and Founder
The Human Impacts Institute 
Tara@HumanImpactsInstitute.org
Office: +1 917 727 9761 
Like us! facebook.com/HumanImpactsInstitute
Follow us! @HumanImpacts
   
Tara DePorte Art, Teaching, and Speaking
TaraDePorte.com
_______________________________
Do LESS. Be more.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#139
