### ISSUE TITLE
drop box problem

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/administrative#88]
we still have a drop box problem
can you reply to her ?
roger
Hi

This is Annick Bureaud, the producer of Audiolats.
I wanted to upload 2 new podcasts for my Disturbances Audiolats and Meta-Life but it says that *my* dropbox is full.
I thought that I were uploading in *your* dropbox.
Roger said that I should contact you as I were not the only one that had faced this issue.

the dropbox url I had is this one
https://www.dropbox.com/home/CD%201.5%20Audiolats

In the meantime, I'll send them to Yvan via wetransfert

Thanks for your help.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#138
